### ISSUE TITLE
请先配置alapi的token

### ISSUE THREAD

**Issue by stonechen03** [6vision/Apilot#13]
[INFO][2023-09-14 10:56:09][chat_channel.py:107] - [WX]receive group at
[ERROR][2023-09-14 10:56:09][Apilot.py:388] - 天气请求失败，错误信息：alapi_token not configured
[INFO][2023-09-14 10:56:09][wechat_channel.py:186] - [WX] sendMsg=Reply(type=TEXT, content=@Stone
请先配置alapi的token), receiver=@@14b31b0e84b6a77274579287ca6c377fc1a74948fc7b4eeeb94effe237c3d6f

<img width="747" alt="image" src="https://github.com/6vision/Apilot/assets/39077997/30b0d747-c3ef-43fc-b037-99a41b02e597">

**Comment by 6vision** [comment]
> [INFO][2023-09-14 10:56:09][chat_channel.py:107] - [WX]receive group at [ERROR][2023-09-14 10:56:09][Apilot.py:388] - 天气请求失败，错误信息：alapi_token not configured [INFO][2023-09-14 10:56:09][wechat_channel.py:186] - [WX] sendMsg=Reply(type=TEXT, content=@stone 请先配置alapi的token), receiver=@@14b31b0e84b6a77274579287ca6c377fc1a74948fc7b4eeeb94effe237c3d6f
> 
> <img alt="image" width="747" src="https://user-images.githubusercontent.com/39077997/267952687-30b0d747-c3ef-43fc-b037-99a41b02e597.png">

部分接口需要配置  参考https://github.com/6vision/Apilot#%E9%85%8D%E7%BD%AE

**Comment by stonechen03** [comment]
<img width="224" alt="image" src="https://github.com/6vision/Apilot/assets/39077997/da73a471-6ab3-44e5-a9e7-638c44c0d5fb">
配置文件有配置的啊

**Comment by 6vision** [comment]
那应该是配置文件没生效 ，或者有问题，可以再找找原因

**Comment by stonechen03** [comment]
docker 安装的，找不到原因没有用了。linkai、tool 和别的插件都正常使用的。

**Comment by 6vision** [comment]
这边正常使用的，插件是最新的吗？

**Comment by stonechen03** [comment]
<img width="717" alt="image" src="https://github.com/6vision/Apilot/assets/39077997/01ae833a-9f33-49e4-8864-bd2f3e87d9fa">

这个版本

**Comment by stonechen03** [comment]
<img width="936" alt="image" src="https://github.com/6vision/Apilot/assets/39077997/82d843d3-cadb-49a7-8a98-25275fda8b6c">
是这个报错问题吗？建议增加一个 requirements.txt 文件。空的也可以试一下

**Comment by yingyuweiying** [comment]
> <img alt="图像" width="936" src="https://private-user-images.githubusercontent.com/39077997/268425957-82d843d3-cadb-49a7-8a98-25275fda8b6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjk4NDUsIm5iZiI6MTcxMDI2OTU0NSwicGF0aCI6Ii8zOTA3Nzk5Ny8yNjg0MjU5NTctODJkODQzZDMtY2FkYi00OWE3LThhOTgtMjUyNzVmZGE4YjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE4NTIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMzNlMWIzZWUzZWFjMzdjMDdhM2JmNTYwY2U5ZGIwNThlMzY4NmY4MjNiZjM0MGY0MGFjMDkzNmYwZjUyYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hXJjXi19V3KEyiG5F7nwBulhwI34S43O164jk5xQQxM">是这个报错问题吗？建议增加一个 requirements.txt 文件。空的也可以试一下

哇 大佬，太厉害了，我刚也是这个问题，谢谢谢谢
