### ISSUE TITLE
https://api.vvhan.com/好像打不开了

### ISSUE THREAD

**Issue by kokojacket** [6vision/Apilot#21]
https://api.vvhan.com/好像打不开了
如何把api换成alapi啊

**Comment by 6vision** [comment]
我看现在恢复正常了，如果要换，需要修改下代码，不同api请求格式不一样，可以问问gpt

**Comment by kokojacket** [comment]
嗯嗯，改好了，全靠一手gpt.小白我太难了

**Comment by ychappyboy** [comment]
> 嗯嗯，改好了，全靠一手gpt.小白我太难了

遇到同样问题，请教下怎么改的啊

**Comment by kokojacket** [comment]
> > 嗯嗯，改好了，全靠一手gpt.小白我太难了
> 
> 遇到同样问题，请教下怎么改的啊

分段发给ai，提供接口和请求方式等等，让他仿照写新的
