### ISSUE TITLE
热榜获取失败

### ISSUE THREAD

**Issue by ychappyboy** [6vision/Apilot#22]
已购买今日热榜套餐，发送抖音热榜等提示热榜获取失败，摸鱼提示moyu_calendar请求失败，其他功能如天气、早报、快递都可以使用

**Comment by 6vision** [comment]
现在再试试呢，应该恢复了

**Comment by 6vision** [comment]
热榜和摸鱼用的是   https://api.vvhan.com/ 免费 接口，看起来好像最近屏蔽了海外ip的样子。alapi热榜需要付费，暂时没有兼容。

**Comment by ychappyboy** [comment]
> 热榜和摸鱼用的是 https://api.vvhan.com/免费接口，看起来最近发光了海外ip的样子。alapi热榜需要付费，暂时没有兼容。
刚刚试过了，还是获取失败，摸鱼提示moyu_calendar

**Comment by 6vision** [comment]
已更新，可以更新代码
