### ISSUE TITLE
星座API出错了

### ISSUE THREAD

**Issue by mela93** [6vision/Apilot#23]
<img width="496" alt="image" src="https://github.com/6vision/Apilot/assets/17722672/e068d3dc-5cff-4963-ac76-0eddb572088e">
<img width="1208" alt="image" src="https://github.com/6vision/Apilot/assets/17722672/c6bdee86-230d-47f1-88c0-c29149c7dcc5">

**Comment by 6vision** [comment]
现在可以了，免费的接口不稳定，失效时候等一两天，站长应该就修复，我加个备用的吧
