### ISSUE TITLE
好奇怪，突然群聊文字回复早报就失效了

### ISSUE THREAD

**Issue by kokojacket** [6vision/Apilot#25]
早报api开启文字回复之后，群聊中会直接无响应，私聊仍会回复
早报api开启图片回复之后，群聊和私聊都正常
![image](https://github.com/6vision/Apilot/assets/74887370/e979d1fa-5412-4391-96c9-59a5addaa400)
![image](https://github.com/6vision/Apilot/assets/74887370/c971e6fc-ecc3-41c1-84a1-09e82fd3b819)
![image](https://github.com/6vision/Apilot/assets/74887370/74555608-f790-4fc8-8344-a5dd3599493f)

**Comment by 6vision** [comment]
你好，不是插件的问题，是腾讯检测屏蔽机制。你可以手动复制私聊的早报信息，发送到群聊，群聊别的成员也看不到你发送的早报消息。明天就好了

**Comment by kokojacket** [comment]
居然还有这种神奇的机制
