### ISSUE TITLE
接口路径不存在了

### ISSUE THREAD

**Issue by couurh** [6vision/Apilot#31]
热榜获取失败，错误信息：{'success': False, 'code': 88888, 'message': '接口路径不存在 请前往  https://api.vvhan.com/  查看免费API接口列表'}

**Comment by 6vision** [comment]
看起来是站长的接口挂了，接口也需要更新一下，等修复哈

**Comment by hidjmax** [comment]
3月20日更新了新的接口，去官网看看就知道了

**Comment by 6vision** [comment]
已更新

**Comment by couurh** [comment]
好了好了
